version: "3.8"
services:
  spattle:
    build: .
    links:
      - 'database:database'
    ports:
      - "8082:3000"
    volumes:
      - .:/spattle
      - /spattle/node_modules
    command: sh -c "mkdir -p dist && touch ./dist/index.js && nodemon --delay 500ms --watch dist ./dist/index.js"
    restart: unless-stopped
  
  transpiler:
    build: .
    volumes:
      - .:/spattle
      - /spattle/node_modules
    command: sh -c "cp index.html dist/index.html && tsc -w"

  database:
    image: bitnami/mongodb:latest
    container_name: mongodb
    hostname: mongodb
    env_file:
      - .env
    environment:
      MONGODB_USERNAME: spattle
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: spattle
    volumes:
      - '.docker/mongodb:/bitnami/mongodb'
    ports:
      - '27017:27017'
