version: "3.8"
services:
  spattle:
    build: .
    ports:
      - "8082:3000"
    volumes:
      - .:/spattle
    restart: unless-stopped
  database:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
          - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
          - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
          - ./.docker/mongodb/data/db/:/data/db/
          - ./.docker/mongodb/data/log/:/var/log/mongodb/
    ports:
      - '27017-27019:27017-27019'
    command: ["-f", "/etc/mongod.conf"]
